spring:
  config:
    import: optional:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/elections
    driver-class-name: org.postgresql.Driver
  application:
    name: elections
server:
  port: 8001