spring:
  config:
    import: optional:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
    driver-class-name: org.postgresql.Driver
  application:
    name: elections


#logging:
#  level:
#    root: DEBUG
server:
  port: 8001